#! /bin/bash
#------------------------------------------------------
#Kaio Barbosa
#ksbarbos
#lab3
#This is a bash script that runs the Lawn.class program
#------------------------------------------------------
echo "compiling Lawn.java"
javac Lawn.java >& Lawn-errs
echo "running Lawn.class"
java Lawn < Lawn-in > Lawn-out
echo "deleting Lawn.class"
rm Lawn.class

